version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:11.0-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: neotour
    ports:
      - "5432:5432"